INSERT INTO USERS(ROLE, USERNAME, PASS, EMAIL, CONTACT, NOOFPEOPLE, OCCUPATION, APTTYPE, PREFERENCES, NEEDFROM) 
VALUES (1, 'JDOE', 'admin', 'jdoe@localhost.com','987654321', 5, 2, '2 BHK 2 BATH', 'GROUND FLOOR', '2015-12-12');

INSERT INTO USERS(ROLE, USERNAME, PASS, EMAIL, CONTACT, NOOFPEOPLE, OCCUPATION, APTTYPE, PREFERENCES, NEEDFROM)
VALUES (2, 'CHITTAKSH', 'chitta', 'chitta@localhost.com','1234567890', 5, 2, '2 BHK 2 BATH', 'TOP FLOOR', '2015-12-12');

INSERT INTO USERS(ROLE, USERNAME, PASS, EMAIL, CONTACT, NOOFPEOPLE, OCCUPATION, APTTYPE, PREFERENCES, NEEDFROM)
VALUES (2, 'NITIN', 'nitin', 'nitin@localhost.com','1234567890', 5, 2, '2 BHK 2 BATH', 'TOP FLOOR', '2015-12-12');

INSERT INTO APARTMENTDETAILS(APARTMENTNO, APTTYPE, FACILITIES, MAXPEOPLE, RENT, DEPOSIT, VACANT, UPDATEDONE) 
VALUES(101, '2 BHK 1 Bath', 'Hot Water 24x7', 3, 1200, 1700, TRUE, CURDATE());

INSERT INTO APARTMENTDETAILS(APARTMENTNO, APTTYPE, FACILITIES, MAXPEOPLE, RENT, DEPOSIT, VACANT, UPDATEDONE) 
VALUES(102, '2 BHK 1 Bath', 'Hot Water 24x7', 3, 1200, 1700, FALSE, CURDATE());

INSERT INTO APPOINTMENTDETAILS(USERID, APTID, STATUS, APPOINTMENTDATE, APPOINTCREATED) 
VALUES(3, 2, 6, CURDATE(), CURDATE());

INSERT INTO RENTDETAILS(APPOINTID, USERID, APTID, LEASETERMINATION, LEASEHOLDERNAME, IDPROOF, RENTRENT, RENTDEPOSIT) 
VALUES(1, 3, 2, DATE_ADD(curdate(), INTERVAL 1 YEAR), 'NITIN RENT', 'Passport', 1200, 1700);