USE cs320;

DROP TABLE IF EXISTS DAYS;
DROP TABLE IF EXISTS TIMESLOT;
DROP TABLE IF EXISTS MEETINGS;


CREATE TABLE DAYS(
ID INT PRIMARY KEY AUTO_INCREMENT,
DAYNAME VARCHAR(20) NOT NULL
);

CREATE TABLE TIMESLOT(
ID INT PRIMARY KEY AUTO_INCREMENT,
TIMEVALUE VARCHAR(20) NOT NULL
);


CREATE TABLE MEETINGS(
ID INT PRIMARY KEY AUTO_INCREMENT,
DAYID INT REFERENCES DAYS(ID),
TIMESLOTID INT REFERENCES TIMESLOT(ID),
NOTES VARCHAR(50) NOT NULL
);
