INSERT INTO  DAYS(DAYNAME) VALUES('Monday');
INSERT INTO  DAYS(DAYNAME) VALUES('Tuesday');
INSERT INTO  DAYS(DAYNAME) VALUES('Wednesday');
INSERT INTO  DAYS(DAYNAME) VALUES('Thursday');
INSERT INTO  DAYS(DAYNAME) VALUES('Friday');

INSERT INTO TIMESLOT(TIMEVALUE) VALUES('9-10');
INSERT INTO TIMESLOT(TIMEVALUE) VALUES('10-11');
